name: Deploy to Firebase Hosting on PR
"on": pull_request

env: # <--- here
  REACT_APP_HOPEETF_MORALIS_APPLICATION_ID: ${{secrets.REACT_APP_HOPEETF_MORALIS_APPLICATION_ID}}
  REACT_APP_HOPEETF_MORALIS_SERVER_URL: ${{secrets.REACT_APP_HOPEETF_MORALIS_SERVER_URL}}

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOPEETF }}"
          projectId: hopeetf
